// <auto-generated />
namespace CIC_WEB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class them_Noi_Dung_va_HowCanWeHelp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(them_Noi_Dung_va_HowCanWeHelp));
        
        string IMigrationMetadata.Id
        {
            get { return "202004290335026_them_Noi_Dung_va_HowCanWeHelp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
